### ISSUE TITLE
TypeError: mergeProps is not a function

### ISSUE THREAD

**Issue by bartvanremortele** [psychobolt/react-paperjs#12]
Hi,

If I try to use the PanAndZoom I'm getting the error `TypeError: mergeProps is not a function
`. I tried to use the exact same component which is being used in the storybook demo but I have the same issue there. I believe it's the ContextProvider which is not injecting `paper` and `mergeProps`.

Any suggestions on how to fix this?

**Comment by mejackreed** [comment]
Are you using `renderWithPaperScope`? If so, I've found you will need to pass through the `paper` prop in `v0.0.57`.

**Comment by psychobolt** [comment]
Hi, before we investigate further... can you specify which version of react-paperjs and react-paperjs-editor are you using?

**Comment by paulodeon** [comment]
I'm getting the same error. Versions are:

"@psychobolt/react-paperjs": "^1.0.0"
"@psychobolt/react-paperjs-editor": "^0.0.12"

https://github.com/psychobolt/react-paperjs/blob/master/packages/react-paperjs-editor/src/components/PanAndZoom/PanAndZoom.component.js appears to be typescript where the rest of the project is JS?

**Comment by psychobolt** [comment]
@paulodeon The type annotations are in [flow js](https://flow.org/).

I have no issues running the example from storybook. Do you have an example code or repository?

**Comment by paulodeon** [comment]
It's a Rails app and a private project so a bit hard to share, however, looking into the yarn file there is no reference to flow?

Perhaps I need to include the flow package somehow?

**Comment by psychobolt** [comment]
@paulodeon Sorry I don't understand why you need reference to flow. Are you referencing and compiling the source code directly? The library is meant to be used without compiling the source files, either with es6 imports or es5 require.

**Comment by paulodeon** [comment]
That could be my misunderstanding.

Here's the code I'm working with:

```js
import React from "react"
import PropTypes from "prop-types"

import { Resizable } from 're-resizable'

import { PaperContainer, Layer, Circle, renderWithPaperScope } from '@psychobolt/react-paperjs'
import { Grid, PanAndZoom } from '@psychobolt/react-paperjs-editor'

const ref = instanceRef => { console.log(instanceRef) }

class AppCanvas extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      width: '100%',
      height: '100%',
    }

    this.container = React.createRef()
  }

  onResizeStop = (event, direction, refToElement) => {
    const width = refToElement.clientWidth;
    const height = refToElement.clientHeight;
    Object.assign(this.container.current.props.paper.view.viewSize, { width, height });
  }

  render() {
    const { width, height } = this.state

    return (
      <Resizable defaultSize={{ width: '100%', height: '100%' }} onResizeStop={this.onResizeStop}>
        <PaperContainer
          ref={this.container}
          canvasProps={{ resize: 'true', style: { width, height } }}
          // onMount={paper => paper.view.element.focus()}
          viewProps={paper => ({
            onResize: () => {
              const { width: vWidth, height: vHeight } = paper.view.viewSize
              this.setState({ width: `${vWidth}px`, height: `${vHeight}px` })
            }
          })}
        >
          <PanAndZoom
            center={[0, 0]}
            prepanStyle={{ cursor: '-webkit-grab' }}
            panStyle={{ cursor: '-webkit-grabbing' }}
            onPanEnabled={() => { console.log('Pan enabled') }}
            onPanDisabled={() => { console.log('Pan disabled') }}
            onZoom={level => { console.log(`Zoom: ${level}`) }}
          >
            {renderWithPaperScope(paper => {
              const { top, left, right, bottom } = paper.view.bounds
              return (
                <Grid
                  ref={ref}
                  width={width}
                  height={height}
                  top={top}
                  left={left}
                  right={right}
                  bottom={bottom}
                  strokeWidth={1 / paper.view.zoom}
                />
              )
            })}
            <Layer ref={ref}>
              <Circle
                ref={ref}
                radius={35}
                strokeColor="black"
                fillColor="white"
              />
            </Layer>
          </PanAndZoom>
        </PaperContainer>
      </Resizable>
    )
  }
}

AppCanvas.propTypes = {
  app: PropTypes.object
};

export default AppCanvas
```

The full error I'm getting is:

Uncaught TypeError: mergeProps is not a function at PanAndScroll.componentDidMount (index.dev.js:1302)

**Comment by psychobolt** [comment]
I've reproduced it, looks like its only happening with the development build.

**Comment by psychobolt** [comment]
I may take my lesson to publish react-paperjs as a __peer__ package dependency. Try out the new version (0.0.13) and let me know. https://www.npmjs.com/package/@psychobolt/react-paperjs-editor/v/0.0.13

**Comment by paulodeon** [comment]
I upgraded the package but I'm still getting the same error.

The dependency has changed to "@psychobolt/react-paperjs" "^0.0.58" instead of 1.0.0 Is that correct?

**Comment by psychobolt** [comment]
Sorry I missed the __peer__ change somehow. Please try again with 0.0.14: https://www.npmjs.com/package/@psychobolt/react-paperjs-editor/v/0.0.14.

I have a hunch that some projects are installing another react-paperjs dependency under react-paperjs-editor. So to resolve the issue, I changed the requirement to __peer__ to ensure only the package at the root project is being used. If installing the new version  doesn't work, you may need to manually remove react-paperjs-editor and install it again. The versioning of which react-paperjs version to use shouldn't have any impact besides either you are using React 16 (v0.0.58) or React 17 (v1.0.0).

**Comment by paulodeon** [comment]
Ok, thanks that seems to have fixed it - the PanAndZoom component now works.

Reinstalling the package also fixed the dependency weirdness
