### ISSUE TITLE
Error Can't resolve dependency

### ISSUE THREAD

**Issue by returnvoid** [psychobolt/react-paperjs#14]
Hi there, I'm trying to use your library and I'm getting this error:

"react": "^16.13.1"
"react-dom": "^16.13.1"

Module not found: Can't resolve 'paper/dist/paper-core'

thanks in advance

**Comment by psychobolt** [comment]
What version of paper do you have installed?

**Comment by returnvoid** [comment]
I have tried 58, 57 and 56, Same issue

**Comment by psychobolt** [comment]
Sorry I was asking for the [paper js](https://www.npmjs.com/package/paper) package version

**Comment by returnvoid** [comment]
I didn't include it :(
so no issue

thanks!
