### ISSUE TITLE
Example for mouse events

### ISSUE THREAD

**Issue by returnvoid** [psychobolt/react-paperjs#15]
Hi!

Do you have examples for implementing mouse events?

thanks

**Comment by psychobolt** [comment]
Here is a simple example of implementing ```LineTool``` from the react-paperjs-editor package: https://github.com/psychobolt/react-paperjs/blob/master/packages/react-paperjs-editor/src/components/LineTool/LineTool.component.js

We can create a [Tool](http://paperjs.org/reference/tool/) component that handles mouse/keyboard handlers

```
import { Tool } from '@psychobolt/react-paperjs';

export default ({ onMouseDown, onMouseDrag, onMouseUp, ...rest }) => (
  <Tool
      onMouseDown={onMouseDown}
      onMouseDrag={onMouseDrag}
      onMouseUp={onMouseUp}
      {...rest}
  />
);
```

**Comment by returnvoid** [comment]
Thanks for fast reply. Going to try this solution

Thanks again!
