### ISSUE TITLE
Loading SVGs

### ISSUE THREAD

**Issue by paulodeon** [psychobolt/react-paperjs#19]
Any thoughts on how to load SVGs using react-paperjs?

So far I've got this which does indeed load the svg and return a Group but I believe this is a paperjs group and not a React Node. 

Is there some way to convert the native node into a React one?

```javascript
  onMount = () => {
    const svg = this.imageRef.current.importSVG(imagePath('./canvas/website.svg'), { onLoad: this.onImageLoad, insert: false })
  }

  onImageLoad = (item, svg) => {
    console.log(item, svg)
  }
render() {
return (
                    <Rectangle
                      center={center}
                      ref={this.imageRef}
                    />
)
```

**Comment by psychobolt** [comment]
You can use native SVGs in React DOM reconciler, but they will have to reside outside the Paper container (as any nodes not recognized by the reconciler). If you need to do any preprocessing before they get rendered into Paper, you should handle it before the import.

**Comment by paulodeon** [comment]
Thanks for that! 

That example helped me get there.

I struggled a bit to get that working I think due to differences in setup and inexperience with functional React. 

Also I didn't need to process the SVGs, so in the end I got something working that looked like this:

```javascript
import DatabaseIcon from '-!raw-loader!../images/canvas/database.svg'
import WebsiteIcon from '-!raw-loader!../images/canvas/website.svg'

const SVGGroup = forwardRef((props) => {
  const { svg, ...rest } = props
  const ref = useRef()
  useEffect(() => ref.current.importSVG(svg), [ref])
  return <Group ref={ref} {...rest} />
})

return (
  <Group applyMatrix={false}>
    <SVGGroup
      applyMatrix={false}
      pivot={[24, 24]}
      position={0, 0}
      svg={WebsiteIcon}
    />  
    <SVGGroup
      applyMatrix={false}
      pivot={[20, 32]}
      position={[100, 100]}
      svg={DatabaseIcon}
    />
  </Group>
)

```
