### ISSUE TITLE
SSR and GatsbyJS and jsdom

### ISSUE THREAD

**Issue by amcc** [psychobolt/react-paperjs#22]
GatsbyJS has an SSR issue (to do with Paper itself, but perhaps there's a way round you can help with)
Issue described here: https://github.com/paperjs/paper.js/issues/1483

The error I get on build with gatsby is below:

```
ERROR Generating SSR bundle failed

If you're trying to use a package make sure that 'jsdom/lib/jsdom/living/generated/utils' is installed. If you're trying to use a local file make sure that the path is correct.

Can't resolve 'jsdom/lib/jsdom/living/generated/utils' in '/usr/src/app/www/node_modules/paper/dist/node'
```

Repo here to reproduce: https://github.com/amcc/gatsby-paper-fiber

**Comment by psychobolt** [comment]
This solution seems to work for build: https://github.com/gatsbyjs/gatsby/issues/13219#issuecomment-792964209 . Have you tried it?

**Comment by amcc** [comment]
Thanks so much for the help here. This solves the jsdom issue. You also need @loadable/component to prevent build/ssr issues too. 

Interestingly because we need named imports I couldn't use @loadable/component easily for the multiple named imports needed with this project (unless there's a trick i'm missing) so I made a component with react-paperjs normally then imported that component with @loadable/component. If there is a way to use @loadable/component or similar deferred loader directly with multiple named imports let me know.

Hope this helps someone else and thanks for the response....

For GatsbyJS - Create a component exactly like the documentation in this repo, add the code to gatsby-node.js as above, code below:

```js
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: { rules: [{ test: /node_modules\/paper/, use: loaders.null() }] },
    });
  }
};
```

Import your react-paperjs component with @loadable/component as below:
```js
const PaperComponent = loadable(
  async () => (await import("../components/Paper")).PaperComponent,
  {
    fallback: <>Loading...</>,
  }
);
```

You can then use it normally in things like Gatsby and Next with SSR.

I chose a named export/import for my react-paperjs component, but if its a default export the import is simpler, docs here: https://loadable-components.com/

@psychobolt if the above all sounds like reasonable instructions and info I hope its useful.

I made a simple gatsby starter site with the above code here:
https://github.com/amcc/gatsby-paper-fiber
