### ISSUE TITLE
Error in function getNearestMountedFiber

### ISSUE THREAD

**Issue by amcc** [psychobolt/react-paperjs#23]
I'm getting this error when moving a component i made with your repo to a project running react 16.14.0:

Error in function getNearestMountedFiber in ./node_modules/@psychobolt/react-paperjs/dist/index.dev.js:2178

Runs fine in React 17

**Comment by amcc** [comment]
i see it recommends react 17, is this also a requirement?

**Comment by psychobolt** [comment]
1.0.0 and above requires React 17
