### ISSUE TITLE
Issue in extending PaperRenderer

### ISSUE THREAD

**Issue by im-hamza-dev** [psychobolt/react-paperjs#25]
I am working to add raster feature in app, so looking for the extend feature but documentation is quite limited for me
Any idea what would be the structure of MyCustomStencilComponent here

My code:
![image](https://user-images.githubusercontent.com/32700351/147699558-a63ed5ee-b22a-45c4-8409-5ce607d1d301.png)

Reference:
![image](https://user-images.githubusercontent.com/32700351/147699622-77584274-885e-4e75-8b23-8f67d345f1bc.png)

**Comment by psychobolt** [comment]
MyCustomStencilComponent is just alias for a constant string variable that you define in your renderer. For example, in the reference above I could use TYPE_NAME in the App component.
```jsx
import MyCustomStencil from './MyCustomStencil';

const TYPE_NAME = 'myStencil';

class MyPaperRenderer extends PaperRenderer {
  getInstanceFactory() {
    return { 
      ...this.defaultTypes, /* 
        refer to default types
        see https://github.com/psychobolt/react-paperjs/blob/master/src/Paper.types.js#L42 
      */
      [TYPE_NAME]: (props, paper) => new MyCustomStencil(props),
    };
  }
}

const App = (props) => (
   <PaperContainer renderer={MyPaperRenderer}>
     <TYPE_NAME />
   </PaperContainer>
);
```
You can look at the reference, and see there is a link to [default types](https://github.com/psychobolt/react-paperjs/blob/master/src/Paper.types.js#L42).

There is no specific structure for the class `MyCustomStencil`, but its expected you composite it so it extends Paper's prototypes such as from [Item](http://paperjs.org/reference/item/) or `Group`. Then the raster is instantiated and have proper methods to append to the tree for during `react-paperjs`' reconciler's lifecycle. (see [host config](https://github.com/psychobolt/react-paperjs/blob/master/src/Paper.renderer.js#L40)). However, if you need further advanced customization, lucky enough you already have access to [extend the renderer's host config](https://github.com/psychobolt/react-paperjs#defaulthostconfig-).

**Comment by im-hamza-dev** [comment]
Oh, Thanks a lot @psychobolt , I was close and now issue resolved
Successfully extended.

**Comment by psychobolt** [comment]
@im-hamza-dev No problem, I just merged a related [PR](https://github.com/psychobolt/react-paperjs/pull/3). There is a [new version (1.0.3)](https://www.npmjs.com/package/@psychobolt/react-paperjs/v/1.0.3) out now with these changes.
